### ISSUE TITLE
ブラウザ起動後見出しは出てますが、内容は出ないです

### ISSUE THREAD

**Issue by paper5487** [negokaz/spark-hands-on-development#4]
お疲れ様です。参加者の簡です。

MAC環境で手順を沿って、実施したが、
最後の部分、フロントエンドサーバーを起動させた後、警告のメッセージが出てます。
（Connection refusedされてるらしいです。）
ブラウザ起動後見出しは出てますが、内容は出ないです

(Server started, use Ctrl+D to stop and go back to the console...)

Warning: node.js detection failed, sbt will use the Rhino based Trireme JavaScript engine instead to run JavaScript assets compilation, which in some cases may be orders of magnitude slower than using node.js.
[info] - akka.event.slf4j.Slf4jLogger - Slf4jLogger started
[info] - Remoting - Starting remoting
[info] - Remoting - Remoting started; listening on addresses :[akka.tcp://application@127.0.0.1:2551]
[info] - Remoting - Remoting now listens on addresses: [akka.tcp://application@127.0.0.1:2551]
[info] - play.api.Play - Application started (Dev)
[warn] - akka.remote.ReliableDeliverySupervisor - Association with remote system [akka.tcp://backend@127.0.0.1:2552] has failed, address is now gated for [5000] ms. Reason: [Association failed with [akka.tcp://backend@127.0.0.1:2552]] Caused by: [Connection refused: /127.0.0.1:2552]
[info] - akka.remote.RemoteActorRefProvider$RemoteDeadLetterActorRef - Message [com.example.tagrank.api.package$AnalyzeRanking$] from Actor[akka://application/system/websockets/27/handler#703140361] to Actor[akka://application/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.

どうすれば良いのか、ご教授願います。

よろしくお願いいたします。

**Comment by negokaz** [comment]
`./activator backend/run` で起動させたバックエンドサーバー側ではどのようなログが出力されていますか？
エラーなど出てないでしょうか？

**Comment by paper5487** [comment]
./activator backend/run
の方は特に問題ないそうです。

Nick-iMac:spark-hands-on-development paper5487$ ./activator run
[info] Loading project definition from /Users/paper5487/spark-hands-on-development/project
[info] Set current project to twitter-hashtag-ranking-frontend (in build file:/Users/paper5487/spark-hands-on-development/)

--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

**Comment by negokaz** [comment]
添付して頂いたログはフロントエンドのログですね。
バックエンド側のログを添付して頂けますか？

**Comment by paper5487** [comment]
失礼しました。
バックエンドサーバー側のログは下記となります。

Nick-iMac:spark-hands-on-development paper5487$ ./activator backend/run
[info] Loading project definition from /Users/paper5487/spark-hands-on-development/project
[info] Set current project to twitter-hashtag-ranking-frontend (in build file:/Users/paper5487/spark-hands-on-development/)
[info] Running com.example.tagrank.backend.Backend local[4]
[INFO] [11/06/2015 12:31:24.440] [run-main-0] [Remoting] Starting remoting
[INFO] [11/06/2015 12:31:26.018] [run-main-0] [Remoting] Remoting started; listening on addresses :[akka.tcp://backend@127.0.0.1:2552]
[INFO] [11/06/2015 12:31:26.021] [run-main-0] [Remoting] Remoting now listens on addresses: [akka.tcp://backend@127.0.0.1:2552]
[INFO] [11/06/2015 12:31:30.442] [backend-akka.actor.default-dispatcher-3] [akka.tcp://backend@127.0.0.1:2552/user/rankingAnalyzer] === RankingAnalyzer started ===

よろしくお願いいたします。

**Comment by negokaz** [comment]
バックエンドで下記のログが出てからブラウザでアクセスしてもらえますか？

> [INFO] [11/06/2015 12:31:26.021] [run-main-0] [Remoting] Remoting now listens on addresses: [akka.tcp://backend@127.0.0.1:2552]

**Comment by negokaz** [comment]
frontend と backend は別のコンソールで起動する必要がありました。(どちらも起動している状態にするため)
